service: billyidol

plugins:
  - aws-amplify-serverless-plugin

custom:
  stage: beta
  amplify:
    - filename: front-end/src/App.js
      type: javascript

package:
  exclude:
    - front-end/node_modules/**
    - front-end/amplify/**
    - front-end/public/**
    - front-end/src/**
    - front-end/yarn.lock

provider:
  name: aws
  runtime: nodejs12.x
  stage: beta
  region: eu-west-1

functions:
  hello:
    handler: handler.hello

  